// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/lib/service/bible_reader_launch_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bible_feed/service/platform_service.dart' as _i2;
import 'package:bible_feed/service/url_launch_service.dart' as _i4;
import 'package:flutter/foundation.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PlatformService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformService extends _i1.Mock implements _i2.PlatformService {
  @override
  _i3.TargetPlatform get currentPlatform =>
      (super.noSuchMethod(
            Invocation.getter(#currentPlatform),
            returnValue: _i3.TargetPlatform.android,
            returnValueForMissingStub: _i3.TargetPlatform.android,
          )
          as _i3.TargetPlatform);

  @override
  bool get isHapticAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isHapticAvailable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAndroid =>
      (super.noSuchMethod(
            Invocation.getter(#isAndroid),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isIOS =>
      (super.noSuchMethod(
            Invocation.getter(#isIOS),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [UrlLaunchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLaunchService extends _i1.Mock implements _i4.UrlLaunchService {
  @override
  _i5.Future<bool> canLaunchUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#canLaunchUrl, [url]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> launchUrl(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#launchUrl, [url]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
