// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/service/feed_advance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:bible_feed/model/feed.dart' as _i3;
import 'package:bible_feed/service/chapter_split_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChapterSplitService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChapterSplitService extends _i1.Mock
    implements _i2.ChapterSplitService {
  @override
  int getNextVerse(_i3.FeedState? state) =>
      (super.noSuchMethod(
            Invocation.method(#getNextVerse, [state]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String getLabel(_i3.FeedState? state) =>
      (super.noSuchMethod(
            Invocation.method(#getLabel, [state]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getLabel, [state]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#getLabel, [state]),
            ),
          )
          as String);
}
