include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.config.dart'
    - '**.mocks.dart'

  # This dcl plugin uses far too cpu and ram on M1 Air base model!
  # Also has a bug where a 2nd connection does not work.
  #
  # plugins:
  #   - dart_code_linter

dart_code_linter:
  extends:
    - package:dart_code_linter/presets/metrics_recommended.yaml
    - package:dart_code_linter/presets/all.yaml
  metrics:
    halstead-volume: 1000
    maintainability-index: 40
    number-of-methods: 12
  rules:
    # dart
    - arguments-ordering: false
    - avoid-ignoring-return-values: false
    - avoid-passing-async-when-sync-expected: false
    - format-comment: false
    - member-ordering: false
    - newline-before-return: false
    - no-magic-number:
        allowed: [0, 0.5, 1]
    - prefer-moving-to-variable: false
    # flutter
    - prefer-extracting-callbacks: false

formatter:
  page_width: 120

linter:
  rules:
    avoid_print: true
    # document_ignores: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_relative_imports: true
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
