include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**.config.dart'
    - '**.mocks.dart'
  plugins:
    - dart_code_linter

dart_code_linter:
  extends:
    - package:dart_code_linter/presets/metrics_recommended.yaml
  metrics:
    halstead-volume: 1000
    maintainability-index: 40
    number-of-methods: 12
  rules:
    # - arguments-ordering
    - avoid-dynamic
    - avoid-late-keyword
    # - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - avoid-nested-conditional-expressions
    # - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    # - prefer-moving-to-variable
    # - prefer-match-file-name

formatter:
  page_width: 120

linter:
  rules:
    avoid_print: true
    # document_ignores: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_relative_imports: true
    unnecessary_breaks: true
    use_key_in_widget_constructors: false
