targets:
  $default:
    sources:
      - integration_test/**
      - lib/**
      - test/**
      # It is important to include these in the default target.
      - pubspec.*
      - $package$

    builders:
      # Sometimes the package name does not match the builder name.
      # In such case, refer to builder by {package_name}:{builder_key}.
      dart_mappable_builder:
        generate_for:
          include:
            - lib/model/*.dart
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/injectable.dart
            - lib/manager/*.dart
            - lib/model/*.dart
            - lib/service/*.dart
            - test/injectable.dart
            - test/golden/stub/**
            - integration_test/injectable.dart
            - integration_test/manager/*.dart
            - integration_test/service/*.dart
      mockito:mockBuilder:
        generate_for:
          include:
            - test/unit/manager/*.dart
            - test/unit/model/*.dart
