targets:
  $default:
    sources:
      - integration_test/**
      - lib/**
      - test/**
      # It is important to include these in the default target.
      - pubspec.*
      - $package$

    builders:
      # Sometimes the package name does not match the builder name.
      # In such case, refer to builder by {package_name}:{builder_key}.
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/injectable.dart
            - lib/model/*.dart
            - lib/service/*.dart
            - test/*.dart
            - integration_test/injectable.dart
      mockito:mockBuilder:
        enabled: true
        generate_for:
          include:
            - test/model/*.dart
            - test/service/*.dart
