// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/bible_readers_certified_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:bible_feed/model/bible_reader.dart' as _i3;
import 'package:bible_feed/model/bible_reader_key.dart' as _i6;
import 'package:bible_feed/model/book_key_externaliser.dart' as _i4;
import 'package:bible_feed/model/url_template.dart' as _i2;
import 'package:flutter/foundation.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUrlTemplate_0 extends _i1.SmartFake implements _i2.UrlTemplate {
  _FakeUrlTemplate_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BibleReader].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockBibleReader extends _i1.Mock implements _i3.BibleReader {
  @override
  _i4.BookKeyExternaliser get bookKeyExternaliser =>
      (super.noSuchMethod(
            Invocation.getter(#bookKeyExternaliser),
            returnValue: _i4.BookKeyExternaliser.identity,
            returnValueForMissingStub: _i4.BookKeyExternaliser.identity,
          )
          as _i4.BookKeyExternaliser);

  @override
  List<_i5.TargetPlatform> get certifiedPlatforms =>
      (super.noSuchMethod(
            Invocation.getter(#certifiedPlatforms),
            returnValue: <_i5.TargetPlatform>[],
            returnValueForMissingStub: <_i5.TargetPlatform>[],
          )
          as List<_i5.TargetPlatform>);

  @override
  _i6.BibleReaderKey get key =>
      (super.noSuchMethod(
            Invocation.getter(#key),
            returnValue: _i6.BibleReaderKey.none,
            returnValueForMissingStub: _i6.BibleReaderKey.none,
          )
          as _i6.BibleReaderKey);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i2.UrlTemplate get urlTemplate =>
      (super.noSuchMethod(
            Invocation.getter(#urlTemplate),
            returnValue: _FakeUrlTemplate_0(
              this,
              Invocation.getter(#urlTemplate),
            ),
            returnValueForMissingStub: _FakeUrlTemplate_0(
              this,
              Invocation.getter(#urlTemplate),
            ),
          )
          as _i2.UrlTemplate);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  bool get isApp =>
      (super.noSuchMethod(
            Invocation.getter(#isApp),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isNone =>
      (super.noSuchMethod(
            Invocation.getter(#isNone),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
