// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/catchup_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i4;

import 'package:bible_feed/manager/catchup_setting_manager.dart' as _i2;
import 'package:bible_feed/manager/feeds_advance_manager.dart' as _i6;
import 'package:bible_feed/manager/midnight_manager.dart' as _i9;
import 'package:bible_feed/model/feeds_advance_state.dart' as _i8;
import 'package:bible_feed/service/date_time_service.dart' as _i5;
import 'package:bible_feed/service/store_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CatchupSettingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatchupSettingManager extends _i1.Mock
    implements _i2.CatchupSettingManager {
  @override
  bool get canEnable =>
      (super.noSuchMethod(
            Invocation.getter(#canEnable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isEnabledByDefault =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabledByDefault),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get storeKey =>
      (super.noSuchMethod(
            Invocation.getter(#storeKey),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#storeKey),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#storeKey),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get subtitle =>
      (super.noSuchMethod(
            Invocation.getter(#subtitle),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
          )
          as String);

  @override
  bool get isEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set isEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i5.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}

/// A class which mocks [FeedsAdvanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsAdvanceManager extends _i1.Mock
    implements _i6.FeedsAdvanceManager {
  @override
  bool get hasEverAdvanced =>
      (super.noSuchMethod(
            Invocation.getter(#hasEverAdvanced),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.Future<_i8.FeedsAdvanceState> advance() =>
      (super.noSuchMethod(
            Invocation.method(#advance, []),
            returnValue: _i7.Future<_i8.FeedsAdvanceState>.value(
              _i8.FeedsAdvanceState.notAllRead,
            ),
            returnValueForMissingStub: _i7.Future<_i8.FeedsAdvanceState>.value(
              _i8.FeedsAdvanceState.notAllRead,
            ),
          )
          as _i7.Future<_i8.FeedsAdvanceState>);

  @override
  _i7.Future<_i8.FeedsAdvanceState> maybeAdvance() =>
      (super.noSuchMethod(
            Invocation.method(#maybeAdvance, []),
            returnValue: _i7.Future<_i8.FeedsAdvanceState>.value(
              _i8.FeedsAdvanceState.notAllRead,
            ),
            returnValueForMissingStub: _i7.Future<_i8.FeedsAdvanceState>.value(
              _i8.FeedsAdvanceState.notAllRead,
            ),
          )
          as _i7.Future<_i8.FeedsAdvanceState>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MidnightManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMidnightManager extends _i1.Mock implements _i9.MidnightManager {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreService extends _i1.Mock implements _i10.StoreService {
  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  DateTime? getDateTime(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDateTime, [key]),
            returnValueForMissingStub: null,
          )
          as DateTime?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i7.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDateTime(String? key, DateTime? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDateTime, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i7.Future<bool>.value(false),
            returnValueForMissingStub: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
