// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/catchup_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;
import 'dart:ui' as _i3;

import 'package:bible_feed/manager/app_lifecycle_manager.dart' as _i2;
import 'package:bible_feed/manager/catchup_setting_manager.dart' as _i4;
import 'package:bible_feed/manager/feeds_advance_manager.dart' as _i9;
import 'package:bible_feed/manager/feeds_manager.dart' as _i7;
import 'package:bible_feed/manager/midnight_manager.dart' as _i11;
import 'package:bible_feed/model/feed.dart' as _i8;
import 'package:bible_feed/model/feeds_advance_state.dart' as _i10;
import 'package:bible_feed/model/priority.dart' as _i12;
import 'package:bible_feed/service/date_time_service.dart' as _i6;
import 'package:bible_feed/service/store_service.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLifecycleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLifecycleManager extends _i1.Mock
    implements _i2.AppLifecycleManager {
  @override
  void runCallbacks() => super.noSuchMethod(
    Invocation.method(#runCallbacks, []),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(
    _i3.VoidCallback? callback, {
    _i2.AppLifecyclePriority? priority = _i2.AppLifecyclePriority.normal,
  }) => super.noSuchMethod(
    Invocation.method(#onResume, [callback], {#priority: priority}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CatchupSettingManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCatchupSettingManager extends _i1.Mock
    implements _i4.CatchupSettingManager {
  @override
  bool get canEnable =>
      (super.noSuchMethod(
            Invocation.getter(#canEnable),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isEnabledByDefault =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabledByDefault),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get storeKeyFragment =>
      (super.noSuchMethod(
            Invocation.getter(#storeKeyFragment),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#storeKeyFragment),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#storeKeyFragment),
            ),
          )
          as String);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  String get subtitle =>
      (super.noSuchMethod(
            Invocation.getter(#subtitle),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#subtitle),
            ),
          )
          as String);

  @override
  bool get isEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set isEnabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEnabled, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i6.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}

/// A class which mocks [FeedsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsManager extends _i1.Mock implements _i7.FeedsManager {
  @override
  bool get areChaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#areChaptersRead),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get chaptersToRead =>
      (super.noSuchMethod(
            Invocation.getter(#chaptersToRead),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i8.Feed> get feeds =>
      (super.noSuchMethod(
            Invocation.getter(#feeds),
            returnValue: <_i8.Feed>[],
            returnValueForMissingStub: <_i8.Feed>[],
          )
          as List<_i8.Feed>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedsAdvanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsAdvanceManager extends _i1.Mock
    implements _i9.FeedsAdvanceManager {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.FeedsAdvanceState advance() =>
      (super.noSuchMethod(
            Invocation.method(#advance, []),
            returnValue: _i10.FeedsAdvanceState.notAllRead,
            returnValueForMissingStub: _i10.FeedsAdvanceState.notAllRead,
          )
          as _i10.FeedsAdvanceState);

  @override
  _i10.FeedsAdvanceState maybeAdvance() =>
      (super.noSuchMethod(
            Invocation.method(#maybeAdvance, []),
            returnValue: _i10.FeedsAdvanceState.notAllRead,
            returnValueForMissingStub: _i10.FeedsAdvanceState.notAllRead,
          )
          as _i10.FeedsAdvanceState);

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MidnightManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockMidnightManager extends _i1.Mock implements _i11.MidnightManager {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(
    _i3.VoidCallback? listener, {
    _i12.Priority? priority = _i12.Priority.normal,
  }) => super.noSuchMethod(
    Invocation.method(#addListener, [listener], {#priority: priority}),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreService extends _i1.Mock implements _i13.StoreService {
  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  DateTime? getDateTime(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDateTime, [key]),
            returnValueForMissingStub: null,
          )
          as DateTime?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i14.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  _i14.Future<bool> setDateTime(String? key, DateTime? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDateTime, [key, value]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  _i14.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  _i14.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);

  @override
  _i14.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i14.Future<bool>.value(false),
            returnValueForMissingStub: _i14.Future<bool>.value(false),
          )
          as _i14.Future<bool>);
}
