// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/feed_tap_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:bible_feed/manager/bible_reader_launch_manager.dart' as _i3;
import 'package:bible_feed/manager/bible_reader_link_manager.dart' as _i6;
import 'package:bible_feed/model/bible_reader.dart' as _i2;
import 'package:bible_feed/model/feed.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBibleReader_0 extends _i1.SmartFake implements _i2.BibleReader {
  _FakeBibleReader_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BibleReaderLaunchManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBibleReaderLaunchManager extends _i1.Mock
    implements _i3.BibleReaderLaunchManager {
  @override
  _i4.Future<bool> isAvailable(_i2.BibleReader? bibleReader) =>
      (super.noSuchMethod(
            Invocation.method(#isAvailable, [bibleReader]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> maybeLaunch(
    _i2.BibleReader? bibleReader,
    _i5.FeedState? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#maybeLaunch, [bibleReader, state]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BibleReaderLinkManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockBibleReaderLinkManager extends _i1.Mock
    implements _i6.BibleReaderLinkManager {
  @override
  bool get isLinked =>
      (super.noSuchMethod(
            Invocation.getter(#isLinked),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.BibleReader get linkedBibleReader =>
      (super.noSuchMethod(
            Invocation.getter(#linkedBibleReader),
            returnValue: _FakeBibleReader_0(
              this,
              Invocation.getter(#linkedBibleReader),
            ),
            returnValueForMissingStub: _FakeBibleReader_0(
              this,
              Invocation.getter(#linkedBibleReader),
            ),
          )
          as _i2.BibleReader);

  @override
  int get linkedBibleReaderIndex =>
      (super.noSuchMethod(
            Invocation.getter(#linkedBibleReaderIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  set linkedBibleReaderIndex(int? value) => super.noSuchMethod(
    Invocation.setter(#linkedBibleReaderIndex, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void unlinkBibleReader() => super.noSuchMethod(
    Invocation.method(#unlinkBibleReader, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
