// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/feeds_advance_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i7;

import 'package:bible_feed/manager/feed_advance_manager.dart' as _i8;
import 'package:bible_feed/manager/feeds_manager.dart' as _i9;
import 'package:bible_feed/model/book.dart' as _i4;
import 'package:bible_feed/model/feed.dart' as _i2;
import 'package:bible_feed/model/reading_list.dart' as _i6;
import 'package:bible_feed/service/date_time_service.dart' as _i3;
import 'package:bible_feed/service/store_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFeedState_1 extends _i1.SmartFake implements _i2.FeedState {
  _FakeFeedState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i3.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}

/// A class which mocks [Feed].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeed extends _i1.Mock implements _i2.Feed {
  @override
  _i4.Book get book =>
      (super.noSuchMethod(
            Invocation.getter(#book),
            returnValue: _i5.dummyValue<_i4.Book>(
              this,
              Invocation.getter(#book),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i4.Book>(
              this,
              Invocation.getter(#book),
            ),
          )
          as _i4.Book);

  @override
  int get bookIndex =>
      (super.noSuchMethod(
            Invocation.getter(#bookIndex),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get chaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#chaptersRead),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double get progress =>
      (super.noSuchMethod(
            Invocation.getter(#progress),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i6.ReadingList get readingList =>
      (super.noSuchMethod(
            Invocation.getter(#readingList),
            returnValue: _i5.dummyValue<_i6.ReadingList>(
              this,
              Invocation.getter(#readingList),
            ),
            returnValueForMissingStub: _i5.dummyValue<_i6.ReadingList>(
              this,
              Invocation.getter(#readingList),
            ),
          )
          as _i6.ReadingList);

  @override
  _i2.FeedState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeFeedState_1(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeFeedState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.FeedState);

  @override
  set state(_i2.FeedState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setBookChapterVerse(int? bookIndex, int? chapter, [int? verse = 1]) =>
      super.noSuchMethod(
        Invocation.method(#setBookChapterVerse, [bookIndex, chapter, verse]),
        returnValueForMissingStub: null,
      );

  @override
  void toggleIsRead() => super.noSuchMethod(
    Invocation.method(#toggleIsRead, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedAdvanceManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedAdvanceManager extends _i1.Mock
    implements _i8.FeedAdvanceManager {
  @override
  void advance(_i2.Feed? feed) => super.noSuchMethod(
    Invocation.method(#advance, [feed]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FeedsManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsManager extends _i1.Mock implements _i9.FeedsManager {
  @override
  bool get areChaptersRead =>
      (super.noSuchMethod(
            Invocation.getter(#areChaptersRead),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.Feed> get feeds =>
      (super.noSuchMethod(
            Invocation.getter(#feeds),
            returnValue: <_i2.Feed>[],
            returnValueForMissingStub: <_i2.Feed>[],
          )
          as List<_i2.Feed>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoreService extends _i1.Mock implements _i10.StoreService {
  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValueForMissingStub: null,
          )
          as bool?);

  @override
  DateTime? getDateTime(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDateTime, [key]),
            returnValueForMissingStub: null,
          )
          as DateTime?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValueForMissingStub: null,
          )
          as double?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getInt, [key]),
            returnValueForMissingStub: null,
          )
          as int?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  _i11.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setDateTime(String? key, DateTime? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDateTime, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}
