// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/feeds_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:bible_feed/manager/feed_store_manager.dart' as _i3;
import 'package:bible_feed/model/feed.dart' as _i2;
import 'package:bible_feed/model/reading_list.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFeed_0 extends _i1.SmartFake implements _i2.Feed {
  _FakeFeed_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FeedStoreManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedStoreManager extends _i1.Mock implements _i3.FeedStoreManager {
  @override
  _i2.Feed load(_i4.ReadingList? readingList) =>
      (super.noSuchMethod(
            Invocation.method(#load, [readingList]),
            returnValue: _FakeFeed_0(
              this,
              Invocation.method(#load, [readingList]),
            ),
            returnValueForMissingStub: _FakeFeed_0(
              this,
              Invocation.method(#load, [readingList]),
            ),
          )
          as _i2.Feed);

  @override
  _i5.Future<void> save(_i4.ReadingList? readingList, _i2.Feed? state) =>
      (super.noSuchMethod(
            Invocation.method(#save, [readingList, state]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
