// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/unit/manager/midnight_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:bible_feed/manager/app_lifecycle_manager.dart' as _i2;
import 'package:bible_feed/service/date_time_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppLifecycleManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLifecycleManager extends _i1.Mock
    implements _i2.AppLifecycleManager {
  @override
  void runCallbacks() => super.noSuchMethod(
    Invocation.method(#runCallbacks, []),
    returnValueForMissingStub: null,
  );

  @override
  void onResume(
    _i3.VoidCallback? callback, {
    _i2.AppLifecyclePriority? priority = _i2.AppLifecyclePriority.normal,
  }) => super.noSuchMethod(
    Invocation.method(#onResume, [callback], {#priority: priority}),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DateTimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDateTimeService extends _i1.Mock implements _i4.DateTimeService {
  @override
  DateTime get now =>
      (super.noSuchMethod(
            Invocation.getter(#now),
            returnValue: _FakeDateTime_0(this, Invocation.getter(#now)),
            returnValueForMissingStub: _FakeDateTime_0(
              this,
              Invocation.getter(#now),
            ),
          )
          as DateTime);
}
