# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "./lanes_android.rb"
import "./lanes_ios.rb"
