# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # get version name + code
  path = "../android/local.properties"
  FileNotFound = Class.new(StandardError)
  if !File.exist?(path) then raise FileNotFound end
  file = File.read(path)
  $vname = /(?<=flutter.versionName=).+/.match(file)[0]
  $vcode = /(?<=flutter.versionCode=).+/.match(file)[0]

  def populate_changelog
    changelog = read_changelog(section_identifier: "[#{$vname}]")
    file = "./metadata/android/en-US/changelogs/#{$vcode}.txt"
    File.open(file, 'w') do |f| f << changelog end
  end

  # ensure_env_vars(env_vars: ['SYMBOLS_FILE_PATH', 'MAPPING_FILE_PATH'])

  desc "Populate changelog"
  lane :populate_changelog do
    populate_changelog
  end

  # desc "Deploy to Google Play internal"
  # lane :gplay_internal do
  #   upload_to_play_store(
  #     mapping_paths: [ENV['SYMBOLS_FILE_PATH'], ENV['MAPPING_FILE_PATH']],
  #     release_status: 'draft',
  #     skip_upload_aab: false,
  #     skip_upload_images: true,
  #     skip_upload_screenshots: true,
  #     track: 'internal',
  #     version_code: $vcode,
  #   )
  # end

  # desc "Promote internal test to closed"
  # lane :gplay_promote_internal_to_closed do
  #   upload_to_play_store(
  #     skip_upload_aab: true,
  #     skip_upload_metadata: true,
  #     skip_upload_changelogs: true,
  #     skip_upload_images: true,
  #     skip_upload_screenshots: true,
  #     track: 'internal',
  #     track_promote_to: "alpha",
  #   )
  # end
end
