source 'https://rubygems.org'

gem 'fastlane'
# gem 'cocoapods'
# gem "abbrev" # needed for ruby 3.4 https://github.com/fastlane/fastlane/issues/21942
# gem 'cocoapods-user-defined-build-types'

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
