// Mocks generated by Mockito 5.4.6 from annotations
// in bible_feed/test/lib/service/auto_advance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bible_feed/service/feed_advance_state.dart' as _i4;
import 'package:bible_feed/service/feeds_advance_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FeedsAdvanceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedsAdvanceService extends _i1.Mock
    implements _i2.FeedsAdvanceService {
  @override
  bool get hasEverAdvanced =>
      (super.noSuchMethod(
            Invocation.getter(#hasEverAdvanced),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<_i4.FeedAdvanceState> forceAdvance() =>
      (super.noSuchMethod(
            Invocation.method(#forceAdvance, []),
            returnValue: _i3.Future<_i4.FeedAdvanceState>.value(
              _i4.FeedAdvanceState.notAllRead,
            ),
            returnValueForMissingStub: _i3.Future<_i4.FeedAdvanceState>.value(
              _i4.FeedAdvanceState.notAllRead,
            ),
          )
          as _i3.Future<_i4.FeedAdvanceState>);

  @override
  _i3.Future<_i4.FeedAdvanceState> maybeAdvance() =>
      (super.noSuchMethod(
            Invocation.method(#maybeAdvance, []),
            returnValue: _i3.Future<_i4.FeedAdvanceState>.value(
              _i4.FeedAdvanceState.notAllRead,
            ),
            returnValueForMissingStub: _i3.Future<_i4.FeedAdvanceState>.value(
              _i4.FeedAdvanceState.notAllRead,
            ),
          )
          as _i3.Future<_i4.FeedAdvanceState>);
}
